### ISSUE TITLE
SSL routines:SSL_write:protocol is shutdown

### ISSUE THREAD

**Issue by valeriy-efimov** [Wisembly/elephant.io#191] opened 2019-05-14 09:29 UTC
after 10 second work
got error "SSL routines:SSL_write:protocol is shutdown"
![image](https://user-images.githubusercontent.com/5989188/57680623-b47e5300-7636-11e9-83a8-b000f1dc1d56.png)
what could be the problem?
my code

```
$client = new Client(new Version2X('https://wss.example.com'));
        $client->initialize();
        $client->emit('key', ['key' => '*********']);
        while (true) {
            $r = $client->read();
            var_dump($r);
}
        $client->close();
```

**Comment by Taluu** [comment] 2019-05-14 13:42
I guess it's because there's a timeout of some sort (it's not a persistent connexion as there's no support for that).

**Comment by valeriy-efimov** [comment] 2019-05-29 12:31
@Taluu  Hi again=) 
I have a problem with your examle
after a couple of hours of work, your example just hangs in place and no longer continues to work. It's like an endless timeout.

`$client->read();`
script work hangs on this line
I ran my script in the supervisor, but due to the fact that here it just hangs up and does not give any errors, the supervisor does not even restart it.

**Comment by peter279k** [comment] 2019-05-29 15:37
@valeriy-efimov, if possible, could you provide your sample code that you execute?

And I don't really know about the supervisor you mention.

Thanks.

**Comment by valeriy-efimov** [comment] 2019-05-29 15:42
@peter279k 

```
        $client = new Client(new Version2X('https://us-wss.live-rates.com/'));
        $client->initialize();
        $client->emit('key', ['key' => env('LIVE_RATES_KEY')]);
        $tries = 0;
        $need_while = true;
        while ($need_while) {
            if($tries>5){
                $need_while = false;
                continue;
            }
            $r = $client->read();
            $array = json_decode($this->getBetween($r,"[","]"));
            $obj = json_decode($array[1]);

            if (!isset($obj->currency)) {
                var_dump($r);
                print("\n");
                $tries++;
            } else {
                $tries = 0;
                echo("Instrument: {$obj->currency} | Ask: {$obj->ask} | Bid: {$obj->bid}");
                print("\n");

            }
        }
        $client->close();
```

**Comment by peter279k** [comment] 2019-05-29 15:52
@valeriy-efimov, thank you for your reply again.

After looking at your code, it seems that you try connecting a remote WebSocket server to get some rate information.

I'm not sure that this problem you mention is caused by remote WebSocket server,

The connection may be closed by remote server.

And I see you use the finite loop to connect server and the loop will leave after trying five times.

It may have possible reason is as follows.

- The response is not valid for the `elephant.io` response parser and this causes the reading work is done.
I think we can try printing the response to look at that.

This `elephant.io` I try on `socket.io` server looks good to me.

And I don't know the request/response behavior on the `socket.io` server is same as this on remote WebSocket server.

**Comment by valeriy-efimov** [comment] 2019-05-30 14:39
![image](https://user-images.githubusercontent.com/5989188/58640456-c6801700-8301-11e9-9ebe-c7b9bd9b3575.png)
Here is an example of the situation.

**Closed** 2019-06-03 10:34 UTC
Labels: support

**Comment by peter279k** [comment] 2019-06-03 10:42
@valeriy-efimov, sorry. I cannot reproduce issue easily because it seems that this WebSocket provider is private.

And the `elephant.io` only support `socket.io` at this moment.
