### ISSUE TITLE
Always receive 42 string in socket.io 1.3.5

### ISSUE THREAD

**Issue by mr-moon** [Wisembly/elephant.io#100] opened 2015-03-23 15:03 UTC
```
$client = new Client(new Version1X('https://127.0.0.1:3000'));
$client2 = new Client(new Version1X('https://127.0.0.1:3000'));
$client->initialize();
$client2->initialize();

$client2->read();
$client->emit('message', ["integration testing socketIO"]);
$r = $client2->read();
```

And `$r` is always '42'.

**Comment by Taluu** [comment] 2015-05-20 09:58
Hi,

As i mentionned in https://github.com/Wisembly/elephant.io/issues/74#issuecomment-56080342, the read method is not implemented correctly, hence your "bug".

I did not have the time yet to investigate this issue any further (or try the solution proposed in https://github.com/Wisembly/elephant.io/issues/74#issuecomment-56103467).

Closing, as this is a duplicate of #74.

**Closed by Taluu** 2015-05-20 09:58 UTC
